# Generated by Django 6.0 on 2026-04-08 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, default='', help_text='Telegram Bot API token from @BotFather', max_length=128)),
                ('chat_id', models.CharField(blank=True, default='', help_text='Target chat or group ID from @IDBot', max_length=64)),
                ('is_active', models.BooleanField(default=False, help_text='Whether to send alerts for new events')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Settings',
                'verbose_name_plural': 'Telegram Settings',
            },
        ),
    ]
